spring:
  application:
    name: api-inteligente-spring-ai

  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:apiinteligente}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: ${OPENAI_MODEL:gpt-4o-mini}

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
